### ISSUE TITLE
Install error: cannot find -lpcsclite

### ISSUE THREAD

**Issue by wdavo** [LudovicRousseau/PCSC#34]
I have been trying to  install this package without much luck. I've included the error log and a bunch of other information about my setup, i'm not sure how much of it is relevant.

Running

npm install pcsclite --verbose

The interesting part seems to be:
  
```
g++ -shared -pthread -rdynamic -m32 -L/usr/lib  -Wl,-soname=pcsclite.node -o Release/obj.target/pcsclite.node -Wl,--start-group Release/obj.target/pcsclite/src/addon.o Release/obj.target/pcsclite/src/pcsclite.o Release/obj.target/pcsclite/src/cardreader.o -Wl,--end-group -lpcsclite
/usr/bin/ld: cannot find -lpcsclite
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/pcsclite.node] Error 1
make: Leaving directory `/fortify/node_modules/pcsclite/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.60-linuxkit-aufs
gyp ERR! command "/root/.nvm/versions/node/v8.10.0/bin/node" "/root/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /fortify/node_modules/pcsclite
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

Running 

ld -lpcsclite  --verbose

I see 

````
attempt to open /usr/x86_64-linux-gnu/lib64/libpcsclite.so failed
attempt to open /usr/x86_64-linux-gnu/lib64/libpcsclite.a failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libpcsclite.so failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libpcsclite.a failed
attempt to open //usr/local/lib64/libpcsclite.so failed
attempt to open //usr/local/lib64/libpcsclite.a failed
attempt to open //lib/x86_64-linux-gnu/libpcsclite.so failed
attempt to open //lib/x86_64-linux-gnu/libpcsclite.a failed
attempt to open //lib64/libpcsclite.so failed
attempt to open //lib64/libpcsclite.a failed
attempt to open //usr/lib/x86_64-linux-gnu/libpcsclite.so succeeded
-lpcsclite (//usr/lib/x86_64-linux-gnu/libpcsclite.so)
libpthread.so.0 needed by //usr/lib/x86_64-linux-gnu/libpcsclite.so
found libpthread.so.0 at //lib/x86_64-linux-gnu/libpthread.so.0
libc.so.6 needed by //usr/lib/x86_64-linux-gnu/libpcsclite.so
found libc.so.6 at //lib/x86_64-linux-gnu/libc.so.6
ld-linux-x86-64.so.2 needed by //lib/x86_64-linux-gnu/libpthread.so.0
found ld-linux-x86-64.so.2 at //lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
ld: warning: cannot find entry symbol _start; not setting start address
````

I am running this in a new docker container, running Ubuntu 14.04

The packages installed before running npm install are

apt-get update
apt-get install curl 
apt-get install git 
apt-get install build-essential
apt-get install python
apt-get install g++-multilib
apt-get install libpcsclite-dev

Node is version 8.10.0
Npm is 5.6.0

**Comment by LudovicRousseau** [comment]
pcsc-lite has notthing to do with node.js

Just use ``apt install pcscd``
