### ISSUE TITLE
Error on Electron windows

### ISSUE THREAD

**Issue by Ionut-Milas** [LudovicRousseau/PCSC#46]
Hi guys.
I'm encountering the below error when running electron app on Windows.
I'm using this package ( https://github.com/pokusew/nfc-pcsc ) to connect to an card reader.
Any help would be greatly appreciated!

> Uncaught Error: \\?\C:\Users\ionutmilas\AppData\Local\Temp\7aeba51b-2fba-46a5-a482-8eb4db26026d.tmp.node is not a valid Win32 application\\?\C:\Users\ionutmilas\AppData\Local\Temp\7aeba51b-2fba-46a5-a482-8eb4db26026d.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (\\mac\Home\Desktop\win-unpacked\resources\app.asar\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (\\mac\Home\Desktop\win-unpacked\resources\app.asar\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)

**Comment by LudovicRousseau** [comment]
Since you are using Windows you are NOT using this PCSC software.
